export interface Booking {
	id?: number; // Make id optional since it's generated by the backend
	resourceId: number;
	slotId: number;
	customerName: string;
	customerEmail: string;
	customerPhone: string;
	customerZip?: string;
	status: 'pending' | 'confirmed' | 'cancelled';
	paymentStatus: 'unpaid' | 'paid';
	amount?: number;
	finalAmount?: number; // Add finalAmount property
	resourceName?: string;
	providerName?: string;
	date?: string;
	startTime?: string;
	endTime?: string;
	startTimeStr?: string;
	endTimeStr?: string;
}
